### ISSUE TITLE
A question about my own dataset

### ISSUE THREAD

**Issue by GilgameshD** [gaoxiang12/rgbd-slam-tutorial-gx#2]
我在使用自己的数据集的时候需要手动调整哪一些参数呢？因为使用原本的参数的效果很不好。

**Comment by zzx2GH** [comment]
把parameters.txt中文件路径和你的相机参数修改好就可以了

在 2017-04-12 09:44:58，"Wenhao Ding" <notifications@github.com> 写道：


我在使用自己的数据集的时候需要手动调整哪一些参数呢？因为使用原本的参数的效果很不好。
