### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by Rajat-Arora** [gaoxiang12/rgbd-slam-tutorial-gx#9]
Hello  Xiang Gao,
First of all, I thank you for such a great version 1 of RGB-D slam tutor, and waiting for you to complete tutor2.
* Could you please help me with what data preprocessing should I do if I directly download the raw dataset of NYU Depth Dataset V2?                 https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html
* Could you please share some tools that you might have used while preprocessing the data? 
*  The camera calibration provided by you is for which dataset? If it is not for NYU Depth Dataset V2 where could I find them? 
* Also please help me with the evaluation of the output of the algorithm.

**Comment by gaoxiang12** [comment]
Hi @Rajat-Arora ,

This tutor was written about 8 years ago so I can't remember the details of the data processing steps. I think the NYU dataset provides some tools to convert the RGB-D raw data to visualizable images. If you are looking for a more recent tutorial please check  [slambook-en](https://github.com/gaoxiang12/slambook-en) and the [code](https://github.com/gaoxiang12/slambook2). Hope it would be helpful for you.

Please also check the (EVO)[https://github.com/MichaelGrupp/evo] for evaluating SLAM trajectory precision.
